<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SimpleSmartMail.Business</RootNamespace>
    <AssemblyName>SimpleSmartMail.Business</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SendGrid" Version="9.28.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.35.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleSmartMail.Models\SimpleSmartMail.Models.csproj" />
    <ProjectReference Include="..\SimpleSmartMail.Data\SimpleSmartMail.Data.csproj" />
  </ItemGroup>

</Project>
